apiVersion: v1
items:
- apiVersion: v1
  data:
    .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7ImF1dGgiOiJlR3hsWkdKa09uTlpURmx6VEZrck1FdG1aMlpLVlZKd1R6RmpjVkZ3TDBrMWFGbG1Na3c1T1ZCc01XSjRNall3VlVreFRGbFlielpOWlVaUUszaENRMWh4ZG5BemIwMDRUMFl3V0VjMmNsWnhSVkZRZVVoMFVFZzNZWEpuUFQwPSJ9fX0=
  kind: Secret
  metadata:
    labels:
      app: catalog
      app.kubernetes.io/instance: catalog
      app.kubernetes.io/part-of: coolstore
      component: catalog
      group: com.redhat.cloudnative
      provider: jkube
      version: 1.0-SNAPSHOT
    name: pullsecret-jkube
  type: kubernetes.io/dockerconfigjson
kind: List
metadata:
  resourceVersion: ""
